### ISSUE TITLE
Add certificate expiration dates

### ISSUE THREAD

**Issue by amuessig** [shreddedbacon/go-web-server#3]
Hi,

please add certificate expiration dates to the UI.

Thanks!

**Comment by shreddedbacon** [comment]
That is an interesting one to try and solve.
That information isn't actually stored in credhub (correct me if I am wrong). This interface is basically just doing API calls and displaying the returned data.

Let me think about this.

**Comment by shreddedbacon** [comment]
I don't think this is easily possible, sorry. I am happy for you to help try and figure this out though. 

If there is JavaScript that can decode a certificate to present the expiration date that you know of, I can try and implement it, that way it would be done client side.

Otherwise it would have to be done at page render time server side using Go, which may be a bit more work.

**Comment by shreddedbacon** [comment]
I did a quick test of this in this branch https://github.com/shreddedbacon/credhub-webui/tree/showCertExpiry

See screenshot:
![screenshot from 2018-12-22 20-38-51](https://user-images.githubusercontent.com/9973880/50372832-b6189180-0629-11e9-9388-1bb8a9872938.png)

**Comment by shreddedbacon** [comment]
See this branch that has a potential solution: https://github.com/shreddedbacon/credhub-webui/tree/showCertExpiry

See screenshot:
![screenshot from 2018-12-22 20-48-43](https://user-images.githubusercontent.com/9973880/50372911-004e4280-062b-11e9-987d-6e8518511e82.png)

**Comment by amuessig** [comment]
Looks good, however, I didn't test it yet.

**Comment by shreddedbacon** [comment]
No probem, it was such a trivial change in the end that I merged it in PR #4 the other day.

Release v0.0.3 has this in it. 

The BOSH release will be updated with this version once I get around to setting up the concourse pipeline to build that.

**Comment by shreddedbacon** [comment]
Closing this as it was implemented in v0.0.3, and I have since updated the BOSH release to use the latest v0.0.4 release
