### ISSUE TITLE
Ability to change port from 8443

### ISSUE THREAD

**Issue by rmeharg** [shreddedbacon/go-web-server#5]
I am using your BOSH release and would like to be able to change the default port from 8443, it seems like it is hardcoded in main.go

**Comment by shreddedbacon** [comment]
Hi @RMeharg I just saw this, I will make it configurable.

**Comment by shreddedbacon** [comment]
v0.1.0 has the ability to change the port, bosh release will follow at some stage

**Comment by rmeharg** [comment]
Thank you, very useful!
